Sprint3 bruna
liviaalmeida/PDS pull request #41
Opened 2021-08-23 18:00 UTC by brunacmelo

2021-08-23 19:46 UTC, philipeatela commented
Acho que tem uns erros de lint quebrando o build, se puder dar uma olhada dps.

2021-08-24 14:05 UTC, liviaalmeida requested changes

2021-08-24 14:05 UTC, liviaalmeida commented on puncto-front/.eslintrc.js
> +    "no-mixed-spaces-and-tabs": 0,
Acho que por questão de consistência, não deveríamos misturar tabs e espaços

2021-08-24 18:21 UTC, liviaalmeida approved these changes

2021-08-24 22:22 UTC, merged